baseurl = "https://tothgames.com"
DefaultContentLanguage = "en"
title = "Toth Games"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
disqusShortname = "tothgames-com"
googleAnalytics = "G-3XTSCB5J42"
ignoreFiles = ["code-samples.*"]
publishDir = "docs"

[Params]
  favicon = "favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = false 
  wordCount = false
  useHLJS = true
  socialShare = true
  #delayDisqus = true
  showRelatedPosts = true
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Michael Toth & Brian Toth"
  website = "tothgames.com"
  email = "hello@tothgames.com"
  twitter = "tothgames"
  reddit = "tothgames"
  discord = "mXkszAyX69"
[[menu.main]]
    name = "Legends of the Arena"
    url = "games/loa"
    weight = 1

[[menu.main]]
    name = "Blog"
    url = "posts/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "contact/"
    weight = 4
