baseurl = "https://tothgames.com"
DefaultContentLanguage = "en"
title = "Toth Games"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
disqusShortname = "tothgames-com"
googleAnalytics = "G-3XTSCB5J42"
ignoreFiles = ["code-samples.*"]
publishDir = "docs"

[Params]
  favicon = "favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  rssUrl = "posts/index.xml"
  comments = true
  readingTime = false 
  wordCount = false
  useHLJS = true
  socialShare = true
  showRelatedPosts = true

[Author]
  name = "Michael Toth & Brian Toth"
  website = "tothgames.com"
  email = "hello@tothgames.com"
  twitter = "tothgames"
  reddit = "tothgames"
  discord = "mXkszAyX69"
[[menu.main]]
    name = "Legends of the Arena"
    url = "games/loa"
    weight = 1

[[menu.main]]
    name = "Blog"
    url = "posts/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "contact/"
    weight = 4
